# Generated by Django 4.0.5 on 2022-06-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_order_settled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='serverd',
            new_name='served',
        ),
    ]
